apiVersion: bsctl.dev/v1alpha1
kind: Feed
metadata:
  name: AIEngineering
  labels: {}
include:
- aiagents
- aiengineer
- aiengineering
- agent
- agents
- anthropic
- bedrock
- chatgpt
- claude
- copilot
- deepmind
- evals
- fine tuning
- gemini
- genai
- generative ai
- gpu
- gpus
- hugging face
- llama
- llms
- mistral
- models
- nvidia
- oai
- openai
- poolside
- prompt engineering
- rag
- retrieval augmented generation
- smol
- sonnet
